U1_Hooks.INF: *.ipf
	ipfc /inf Writing_Rexx_Hook.ipf U1_Hooks.INF


out: ../../OUT/OS2Dist.OUT/U1_Hooks.INF
	echo done

../../OUT/OS2Dist.OUT/U1_Hooks.INF: U1_Hooks.INF
	copy U1_Hooks.INF ..\..\OUT\OS2Dist.OUT\U1_Hooks.INF