/**-------------------   Graphics Windows   -------------------**\
 *                                                              
 *	Copyright (C) 1989 by DZ - Moscow, 110.6728		
 *                                                              
 *	Module : Color customize header				
 *
 *	$Log:   C:/c/gw/vcs/custom.h_v  $
 * 
 *    Rev 1.0   29 Apr 1990 16:21:28   dz
 * Initial revision.
 *                                                              
 *	   Rev 1.0	16 Feb 90            			
 *	Initial revision.				
 *                                                              
 *								
\**------------------------------------------------------------**/


#ifndef FONT_H
#	include <font.h>
#endif

/*			Bar.C			*/

extern uint	BAR_TEXT;
extern uint	BAR_BORD;
extern uint	BAR_BACK;


/*			Dir.C			*/


extern uint	DIR_BORD;
extern uint	DIR_BOX;

extern uint	DIR_BACK;
extern uint	DIR_TEXT;
extern uint	DIR_SHAD;

extern uint	DIR_BARB;
extern uint	DIR_BART;
extern uint	DIR_BARS;


/*			EditS.C			*/


extern uint	EDS_BACK;
extern uint	EDS_TEXT;
extern uint	EDS_BORD;
extern uint	EDS_CURS;
extern uint	EDS_HEAD;





































